"""ID3v2 tag writer and generated cover-art tests."""
import struct
from pathlib import Path

import numpy as np
import pytest
import soundfile as sf
from PIL import Image

from lfms.exporter.cover import cover_bytes_for, generate_cover_art
from lfms.exporter.tags import write_mp3_tags
from lfms.generator.composer import Composer
from lfms.generator.plan import GenerationParameters


def _fake_mp3(tmp_path: Path, seconds: float = 0.5) -> Path:
    sr = 24000
    t = np.arange(int(sr * seconds)) / sr
    path = tmp_path / "tone.mp3"
    sf.write(str(path), (0.4 * np.sin(2 * np.pi * 440 * t)).astype(np.float32), sr)
    return path


def _header(path: Path):
    data = path.read_bytes()
    assert data[:3] == b"ID3"
    version = (data[3], data[4])
    size = (
        (data[6] << 21) | (data[7] << 14) | (data[8] << 7) | data[9]
    )
    return data, version, 10 + size


def _frames(data: bytes) -> dict[str, bytes]:
    body = data[10:]
    offset = 0
    frames: dict[str, bytes] = {}
    while offset + 10 <= len(body):
        frame_id = body[offset:offset + 4].decode("ascii", "ignore")
        if not frame_id.strip("\x00"):
            break
        length = struct.unpack(">I", body[offset + 4:offset + 8])[0]
        payload = body[offset + 10:offset + 10 + length]
        frames[frame_id] = payload
        offset += 10 + length
    return frames


def _utf16_text(payload: bytes) -> str:
    encoding = payload[0]
    if encoding == 0:
        return payload[1:].decode("latin-1")
    return payload[1 + 2:-2].decode("utf-16-le")


def _comment_text(payload: bytes) -> str:
    encoding = payload[0]
    rest = payload[4:]
    sep = b"\x00\x00" if encoding else b"\x00"
    description, found, text = rest.partition(sep)
    if not found:
        return ""
    if encoding:
        return text[:-2].decode("utf-16-le").lstrip("\ufeff")
    return text.rstrip(b"\x00").decode("latin-1")


def _apic_image(payload: bytes) -> bytes:
    rest = payload[1:]
    mime_end = rest.index(b"\x00")
    mime = rest[:mime_end].decode("ascii")
    image = rest[mime_end + 3:]  # skip mime NUL + picture type byte + desc NUL
    return mime, image


def _params() -> GenerationParameters:
    params = GenerationParameters(
        seed=7, duration_sec=1.0, genre="AMBIENT",
        moods=("CALM",), intensity=30.0,
    )
    params.validate()
    return params


@pytest.fixture()
def lib():
    from lfms.library import LibraryService

    service = LibraryService(":memory:")
    yield service
    service.close()


def test_mp3_tags_embedded_and_decode_ok(tmp_path):
    path = _fake_mp3(tmp_path)
    params = _params()
    composition = Composer(params).compose()

    before = sf.info(str(path)).duration
    cover, mime = cover_bytes_for(composition)
    write_mp3_tags(
        path,
        title="Midnight Bloom",
        artist="Test Artist",
        album="LFMS Studio - AMBIENT",
        genre="Ambient",
        year="2026",
        comment="Generated by LFMS Studio.",
        cover_bytes=cover,
        cover_mime=mime,
    )

    data, version, end = _header(path)
    assert version == (3, 0)
    frames = _frames(data)
    assert _utf16_text(frames["TIT2"]) == "Midnight Bloom"
    assert _utf16_text(frames["TPE1"]) == "Test Artist"
    assert _utf16_text(frames["TCON"]) == "Ambient"
    assert _comment_text(frames["COMM"]) == "Generated by LFMS Studio."
    apic_mime, image = _apic_image(frames["APIC"])
    assert apic_mime == mime
    assert image[:8] == b"\x89PNG\r\n\x1a\n"

    # leading tag must not break decoding, and audio tail survives intact
    after = sf.info(str(path)).duration
    assert after == pytest.approx(before, rel=0.05)
    tail = path.read_bytes()[end:]
    assert b"ID3" not in (tail[:10] if len(tail) >= 10 else tail)


def test_tag_replaces_existing_leading_id3(tmp_path):
    path = _fake_mp3(tmp_path, seconds=0.4)
    write_mp3_tags(path, title="First")
    _, _, end0 = _header(path)
    tail_before = path.read_bytes()[end0:]
    write_mp3_tags(path, title="Second")
    data, version, end = _header(path)
    assert version == (3, 0)
    assert _utf16_text(_frames(data)["TIT2"]) == "Second"
    # replacement: exactly one ID3 header and identical audio tail
    assert path.read_bytes()[end:] == tail_before
    assert path.read_bytes().count(b"ID3") == 1


def test_non_mp3_suffix_is_noop(tmp_path):
    path = tmp_path / "tone.wav"
    sf.write(str(path), np.zeros(2400, dtype=np.float32), 8000)
    original = path.read_bytes()
    write_mp3_tags(path, title="Skipped")
    assert path.read_bytes() == original


def test_cover_art_deterministic_and_unique(tmp_path):
    params = _params()
    first = generate_cover_art(Composer(params).compose(), tmp_path / "a.png", size=120)
    second = generate_cover_art(Composer(params).compose(), tmp_path / "b.png", size=120)
    assert first.read_bytes() == second.read_bytes()

    changed = GenerationParameters(
        seed=9991, duration_sec=1.0, genre="CINEMATIC",
        moods=("TENSE",), intensity=80.0,
    )
    changed.validate()
    other = generate_cover_art(
        Composer(changed).compose(), tmp_path / "c.png", size=120
    )
    assert other.read_bytes() != first.read_bytes()

    with Image.open(first) as img:
        assert img.size == (120, 120)
        assert img.format == "PNG"


def test_mp3_export_path_embeds_full_tags(lib, tmp_path):
    from lfms.exporter import export_item

    params = _params()
    composition = Composer(params).compose()
    item = lib.register_composition(composition, params, title="Deep Bed")
    item = lib.add_tag(item.id, "artist:Zahra Khan")
    item = lib.add_tag(item.id, "album:Calm Series")

    out = export_item(
        lib, item.id, tmp_path,
        preset="PODCAST", container="MP3", embed_tags=True,
    )
    fp = out.final_path
    assert fp.suffix.lower() == ".mp3"
    data, version, end = _header(fp)
    assert version == (3, 0)
    frames = _frames(data)
    assert _utf16_text(frames["TIT2"]) == "Deep Bed"
    assert _utf16_text(frames["TPE1"]) == "zahra khan"
    assert _utf16_text(frames["TALB"]) == "calm series"  # library lowercases tags
    assert _utf16_text(frames["TCON"]) == "Ambient"
    assert "APIC" in frames
    # export output still decodes as valid audio afterwards
    assert sf.info(str(fp)).duration > 0.5
    # exactly one ID3 tag in the whole file
    assert fp.read_bytes().count(b"ID3") == 1


def test_mp3_export_without_tags_leaves_file_untagged(lib, tmp_path):
    from lfms.exporter import export_item

    params = _params()
    composition = Composer(params).compose()
    item = lib.register_composition(composition, params, title="Bare")
    out = export_item(
        lib, item.id, tmp_path,
        preset="PODCAST", container="MP3", embed_tags=False,
    )
    head = out.final_path.read_bytes()[:11]
    assert head[:3] != b"ID3"
